from __future__ import annotations


def build_runtime_source(modules_literal: str, entry_module: str) -> str:
    return f"""# Auto-generated by pyfuse. Do not edit manually.
from __future__ import annotations

import importlib.abc
import importlib
import importlib.util
import sys
import types


_PYFUSE_MODULES = {modules_literal}
_ENTRY_MODULE_NAME = {entry_module!r}
_ENTRY_MODULE = None


class _PyfuseLoader(importlib.abc.Loader):
    def __init__(self, fullname: str):
        self.fullname = fullname

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        spec = _PYFUSE_MODULES[self.fullname]
        code = spec["code"]
        filename = spec["filename"]
        module.__file__ = filename
        module.__loader__ = self
        module.__package__ = self.fullname if spec["is_package"] else self.fullname.rsplit(".", 1)[0]
        if spec["is_package"]:
            module.__path__ = [f"<pyfuse>/{{self.fullname}}"]

        compiled = compile(code, filename, "exec")
        exec(compiled, module.__dict__)


class _PyfuseFinder(importlib.abc.MetaPathFinder):
    def find_spec(self, fullname, path=None, target=None):
        if fullname not in _PYFUSE_MODULES:
            return None
        spec = _PYFUSE_MODULES[fullname]
        loader = _PyfuseLoader(fullname)
        return importlib.util.spec_from_loader(fullname, loader, is_package=spec["is_package"])


def _install_importer() -> None:
    for finder in sys.meta_path:
        if isinstance(finder, _PyfuseFinder):
            return
    sys.meta_path.insert(0, _PyfuseFinder())


def _load_entry_module():
    global _ENTRY_MODULE
    _install_importer()
    if _ENTRY_MODULE is None:
        _ENTRY_MODULE = importlib.import_module(_ENTRY_MODULE_NAME)
    return _ENTRY_MODULE


def __getattr__(name: str):
    if name.startswith("_"):
        raise AttributeError(name)
    entry_mod = _load_entry_module()
    try:
        return getattr(entry_mod, name)
    except AttributeError as exc:
        raise AttributeError(name) from exc


def __dir__():
    names = set(globals().keys())
    entry_mod = _load_entry_module()
    names.update(dir(entry_mod))
    return sorted(names)


def _run_entry() -> None:
    _install_importer()
    entry_name = _ENTRY_MODULE_NAME
    entry = _PYFUSE_MODULES[entry_name]

    main_mod = types.ModuleType("__main__")
    main_mod.__file__ = entry["filename"]
    main_mod.__package__ = entry_name.rsplit(".", 1)[0] if "." in entry_name else ""
    main_mod.__spec__ = None
    main_mod.__builtins__ = __builtins__
    sys.modules["__main__"] = main_mod

    compiled = compile(entry["code"], entry["filename"], "exec")
    exec(compiled, main_mod.__dict__)


if __name__ == "__main__":
    _run_entry()
"""
